# Generated by Django 4.1.5 on 2023-02-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CakePr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Price', models.IntegerField()),
                ('Img', models.ImageField(upload_to='pic')),
                ('Qty', models.FloatField()),
                ('Discount', models.IntegerField(default=0)),
                ('Discpt', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
